In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [13]:
Nasdaq_100 = pd.read_excel('Nasdaq100companies.xlsx')
Nasdaq_100.head()

   #         Company Symbol  Weight       Price   Chg   % Chg
0  1       Apple Inc   AAPL  11.855      138.10  2.83 -0.0209
1  2  Microsoft Corp   MSFT  11.793      240.44  8.51 -0.0367
2  3  Amazon.com Inc   AMZN   6.546       97.47  3.79 -0.0405
3  4    Alphabet Inc   GOOG   3.915       99.35  5.44 -0.0579
4  5    Alphabet Inc  GOOGL   3.880       98.16  5.11 -0.0549

In [14]:
Nasdaq_100.iloc[:,2]

0       AAPL
1       MSFT
2       AMZN
3       GOOG
4      GOOGL
       ...
96      ALGN
97        ZM
98        ZS
99      RIVN
100     LCID
Name: Symbol, Length: 101, dtype: object

In [15]:
Nasdaq_100_list = Nasdaq_100.iloc[:,2].tolist()
Nasdaq_100_list

['AAPL',
 'MSFT',
 'AMZN',
 'GOOG',
 'GOOGL',
 'NVDA',
 'TSLA',
 'META',
 'PEP',
 'AVGO',
 'COST',
 'CSCO',
 'TMUS',
 'CMCSA',
 'ADBE',
 'TXN',
 'NFLX',
 'AMGN',
 'HON',
 'QCOM',
 'SBUX',
 'INTC',
 'AMD',
 'INTU',
 'GILD',
 'ADP',
 'AMAT',
 'BKNG',
 'ISRG',
 'PYPL',
 'MDLZ',
 'ADI',
 'VRTX',
 'REGN',
 'MRNA',
 'CSX',
 'FISV',
 'LRCX',
 'MU',
 'CHTR',
 'ATVI',
 'KLAC',
 'ASML',
 'MELI',
 'MNST',
 'MAR',
 'SNPS',
 'ORLY',
 'KHC',
 'KDP',
 'CDNS',
 'AEP',
 'CTAS',
 'AZN',
 'NXPI',
 'PANW',
 'ADSK',
 'PDD',
 'EXC',
 'PAYX',
 'DXCM',
 'BIIB',
 'ROST',
 'ABNB',
 'MCHP',
 'IDXX',
 'FTNT',
 'LULU',
 'XEL',
 'ODFL',
 'EA',
 'PCAR',
 'WDAY',
 'MRVL',
 'DLTR',
 'CTSH',
 'CSGP',
 'ILMN',
 'WBA',
 'BKR',
 'ENPH',
 'WBD',
 'GFS',
 'CPRT',
 'JD',
 'VRSK',
 'FAST',
 'CEG',
 'FANG',
 'EBAY',
 'SGEN',
 'SIRI',
 'TEAM',
 'CRWD',
 'ANSS',
 'DDOG',
 'ALGN',
 'ZM',
 'ZS',
 'RIVN',
 'LCID']

In [18]:
hist = yf.download(Nasdaq_100_list, start="2021-01-01", end="2021-12-31", interval = '1d',group_by = 'ticker')

[*********************100%***********************]  101 of 101 completed

1 Failed download:
- CEG: Data doesn't exist for startDate = 1609430400, endDate = 1640880000

In [22]:
hist_df = pd.DataFrame(hist)
hist_df.head()

                           AAPL                                      \
                      Adj Close       Close        High         Low
Date
2020-12-31 00:00:00  131.116043  132.690002  134.740005  131.720001
2021-01-04 00:00:00  127.874939  129.410004  133.610001  126.760002
2021-01-05 00:00:00  129.455978  131.009995  131.740005  128.429993
2021-01-06 00:00:00  125.098267  126.599998  131.050003  126.379997
2021-01-07 00:00:00  129.367020  130.919998  131.630005  127.860001

                                                  ABNB              \
                           Open     Volume   Adj Close       Close
Date
2020-12-31 00:00:00  134.080002   99116600  146.800003  146.800003
2021-01-04 00:00:00  133.520004  143301900  139.149994  139.149994
2021-01-05 00:00:00  128.889999   97664900  148.300003  148.300003
2021-01-06 00:00:00  127.720001  155088000  142.770004  142.770004
2021-01-07 00:00:00  128.360001  109578200  151.270004  151.270004

                                             ...          ZM              \
                           High         Low  ...        High         Low
Date                                         ...
2020-12-31 00:00:00  147.889999  144.509995  ...  351.829987  336.100006
2021-01-04 00:00:00  151.005005  137.000000  ...  363.089996  339.200012
2021-01-05 00:00:00  149.000000  137.250000  ...  365.010010  349.000000
2021-01-06 00:00:00  148.350006  141.110001  ...  352.940002  341.920013
2021-01-07 00:00:00  154.419998  145.261002  ...  354.480011  341.600006

                                                  ZS                          \
                           Open   Volume   Adj Close       Close        High
Date
2020-12-31 00:00:00  351.769989  6559700  199.710007  199.710007  203.000000
2021-01-04 00:00:00  340.399994  8598300  196.089996  196.089996  200.494995
2021-01-05 00:00:00  360.390015  4983500  193.479996  193.479996  197.940002
2021-01-06 00:00:00  351.000000  7124600  184.419998  184.419998  190.300003
2021-01-07 00:00:00  346.000000  5601200  193.050003  193.050003  193.699997


                            Low        Open   Volume
Date
2020-12-31 00:00:00  198.619995  202.250000  1469600
2021-01-04 00:00:00  192.520004  199.720001  3510700
2021-01-05 00:00:00  189.539993  192.369995  2365500
2021-01-06 00:00:00  183.250000  187.529999  2131100
2021-01-07 00:00:00  185.279999  188.095001  1734600

[5 rows x 606 columns]

In [30]:
hist_df.columns = ['_'.join(col).strip() for col in hist_df.columns.values]
hist_df.head()

,AAPL_Adj Close,AAPL_Close,AAPL_High,AAPL_Low,AAPL_Open,AAPL_Volume,ABNB_Adj Close,ABNB_Close,ABNB_High,ABNB_Low,...,ZM_High,ZM_Low,ZM_Open,ZM_Volume,ZS_Adj Close,ZS_Close,ZS_High,ZS_Low,ZS_Open,ZS_Volume
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-31 00:00:00,131.116043,132.690002,134.740005,131.720001,134.080002,99116600,146.800003,146.800003,147.889999,144.509995,...,351.829987,336.100006,351.769989,6559700,199.710007,199.710007,203.000000,198.619995,202.250000,1469600
2021-01-04 00:00:00,127.874939,129.410004,133.610001,126.760002,133.520004,143301900,139.149994,139.149994,151.005005,137.000000,...,363.089996,339.200012,340.399994,8598300,196.089996,196.089996,200.494995,192.520004,199.720001,3510700
2021-01-05 00:00:00,129.455978,131.009995,131.740005,128.429993,128.889999,97664900,148.300003,148.300003,149.000000,137.250000,...,365.010010,349.000000,360.390015,4983500,193.479996,193.479996,197.940002,189.539993,192.369995,2365500
2021-01-06 00:00:00,125.098267,126.599998,131.050003,126.379997,127.720001,155088000,142.770004,142.770004,148.350006,141.110001,...,352.940002,341.920013,351.000000,7124600,184.419998,184.419998,190.300003,183.250000,187.529999,2131100
2021-01-07 00:00:00,129.367020,130.919998,131.630005,127.860001,128.360001,109578200,151.270004,151.270004,154.419998,145.261002,...,354.480011,341.600006,346.000000,5601200,193.050003,193.050003,193.699997,185.279999,188.095001,1734600

In [31]:
hist_df_close = hist_df.filter(regex='Close')
hist_df_close.head()

,AAPL_Adj Close,AAPL_Close,ABNB_Adj Close,ABNB_Close,ADBE_Adj Close,ADBE_Close,ADI_Adj Close,ADI_Close,ADP_Adj Close,ADP_Close,...,WBD_Adj Close,WBD_Close,WDAY_Adj Close,WDAY_Close,XEL_Adj Close,XEL_Close,ZM_Adj Close,ZM_Close,ZS_Adj Close,ZS_Close
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-31 00:00:00,131.116043,132.690002,146.800003,146.800003,500.119995,500.119995,142.607590,147.729996,169.685440,176.199997,...,30.090000,30.090000,239.610001,239.610001,63.088264,66.669998,337.320007,337.320007,199.710007,199.710007
2021-01-04 00:00:00,127.874939,129.410004,139.149994,139.149994,485.339996,485.339996,140.956894,146.020004,162.713135,168.960007,...,30.629999,30.629999,228.080002,228.080002,62.132538,65.660004,359.980011,359.980011,196.089996,196.089996
2021-01-05 00:00:00,129.455978,131.009995,148.300003,148.300003,485.690002,485.690002,143.476379,148.630005,162.260529,168.490005,...,31.520000,31.520000,225.360001,225.360001,61.526917,65.019997,360.829987,360.829987,193.479996,193.479996
2021-01-06 00:00:00,125.098267,126.599998,142.770004,142.770004,466.309998,466.309998,144.123154,149.300003,161.692307,167.899994,...,34.250000,34.250000,220.000000,220.000000,62.889549,66.459999,344.410004,344.410004,184.419998,184.419998
2021-01-07 00:00:00,129.367020,130.919998,151.270004,151.270004,477.739990,477.739990,150.214355,155.610001,162.607193,168.850006,...,34.400002,34.400002,226.210007,226.210007,61.659401,65.160004,342.500000,342.500000,193.050003,193.050003

In [34]:
hist_df_close_return = hist_df_close.pct_change()
hist_df_close_return.head()

,AAPL_Adj Close,AAPL_Close,ABNB_Adj Close,ABNB_Close,ADBE_Adj Close,ADBE_Close,ADI_Adj Close,ADI_Close,ADP_Adj Close,ADP_Close,...,WBD_Adj Close,WBD_Close,WDAY_Adj Close,WDAY_Close,XEL_Adj Close,XEL_Close,ZM_Adj Close,ZM_Close,ZS_Adj Close,ZS_Close
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-04 00:00:00,-0.024719,-0.024719,-0.052112,-0.052112,-0.029553,-0.029553,-0.011575,-0.011575,-0.041090,-0.041090,...,0.017946,0.017946,-0.048120,-0.048120,-0.015149,-0.015149,0.067177,0.067177,-0.018126,-0.018126
2021-01-05 00:00:00,0.012364,0.012364,0.065756,0.065756,0.000721,0.000721,0.017874,0.017874,-0.002782,-0.002782,...,0.029057,0.029057,-0.011926,-0.011926,-0.009747,-0.009747,0.002361,0.002361,-0.013310,-0.013310
2021-01-06 00:00:00,-0.033662,-0.033662,-0.037289,-0.037289,-0.039902,-0.039902,0.004508,0.004508,-0.003502,-0.003502,...,0.086612,0.086612,-0.023784,-0.023784,0.022147,0.022147,-0.045506,-0.045506,-0.046827,-0.046827
2021-01-07 00:00:00,0.034123,0.034123,0.059536,0.059536,0.024512,0.024512,0.042264,0.042264,0.005658,0.005658,...,0.004380,0.004380,0.028227,0.028227,-0.019560,-0.019561,-0.005546,-0.005546,0.046795,0.046795

In [37]:
hist_df_close_return.columns = [x.split('_')[0]+'_daily_return' for x in hist_df_close_return.columns]
hist_df_close_return.head()

,AAPL_daily_return,AAPL_daily_return,ABNB_daily_return,ABNB_daily_return,ADBE_daily_return,ADBE_daily_return,ADI_daily_return,ADI_daily_return,ADP_daily_return,ADP_daily_return,...,WBD_daily_return,WBD_daily_return,WDAY_daily_return,WDAY_daily_return,XEL_daily_return,XEL_daily_return,ZM_daily_return,ZM_daily_return,ZS_daily_return,ZS_daily_return
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-04 00:00:00,-0.024719,-0.024719,-0.052112,-0.052112,-0.029553,-0.029553,-0.011575,-0.011575,-0.041090,-0.041090,...,0.017946,0.017946,-0.048120,-0.048120,-0.015149,-0.015149,0.067177,0.067177,-0.018126,-0.018126
2021-01-05 00:00:00,0.012364,0.012364,0.065756,0.065756,0.000721,0.000721,0.017874,0.017874,-0.002782,-0.002782,...,0.029057,0.029057,-0.011926,-0.011926,-0.009747,-0.009747,0.002361,0.002361,-0.013310,-0.013310
2021-01-06 00:00:00,-0.033662,-0.033662,-0.037289,-0.037289,-0.039902,-0.039902,0.004508,0.004508,-0.003502,-0.003502,...,0.086612,0.086612,-0.023784,-0.023784,0.022147,0.022147,-0.045506,-0.045506,-0.046827,-0.046827
2021-01-07 00:00:00,0.034123,0.034123,0.059536,0.059536,0.024512,0.024512,0.042264,0.042264,0.005658,0.005658,...,0.004380,0.004380,0.028227,0.028227,-0.019560,-0.019561,-0.005546,-0.005546,0.046795,0.046795

In [41]:
hist_df_close_return = hist_df_close_return.iloc[:,::2]
hist_df_close_return.head()

,AAPL_daily_return,ADBE_daily_return,ADP_daily_return,AEP_daily_return,AMAT_daily_return,AMGN_daily_return,ANSS_daily_return,ATVI_daily_return,AZN_daily_return,BKNG_daily_return,...,REGN_daily_return,ROST_daily_return,SGEN_daily_return,SNPS_daily_return,TMUS_daily_return,TXN_daily_return,VRTX_daily_return,WBD_daily_return,XEL_daily_return,ZS_daily_return
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-04 00:00:00,-0.024719,-0.029553,-0.041090,-0.020776,0.006605,-0.014179,-0.016850,-0.031772,0.010602,-0.028371,...,-0.000517,-0.046739,-0.038312,-0.017513,-0.017946,-0.011637,-0.029238,0.017946,-0.015149,-0.018126
2021-01-05 00:00:00,0.012364,0.000721,-0.002782,-0.001349,0.031426,0.004853,0.006039,0.008788,0.003563,0.011086,...,0.001222,0.000854,0.003384,0.016451,-0.004380,0.007335,-0.003705,0.029057,-0.009747,-0.013310
2021-01-06 00:00:00,-0.033662,-0.039902,-0.003502,0.007982,0.013728,0.024104,-0.027596,-0.029662,0.004142,0.028217,...,-0.027635,0.043697,-0.013314,-0.035498,-0.002427,0.004957,-0.008443,0.086612,0.022147,-0.046827
2021-01-07 00:00:00,0.034123,0.024512,0.005658,-0.026681,0.041066,0.003301,0.043212,0.018977,-0.014143,-0.004427,...,0.023634,-0.002208,0.057631,0.036604,0.012621,0.022653,0.027576,0.004380,-0.019560,0.046795

In [42]:
hist_df_close_return.to_csv('Nasdaq_100_Daily.csv')